# Generated by Django 4.1.4 on 2023-02-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_team_remove_project_icon_teamuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
