# Generated by Django 4.1.4 on 2023-02-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_user_id_task_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
